version: '3'
services:
  ruby:
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    hostname: ruby
    ports:
      - 80:80
    volumes:
      - ./ruby:/ruby
    tty: true
    links:
      - kafka1
      - kafka2

  zookeeper1:
    image: wurstmeister/zookeeper
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181

  zookeeper2:
    image: wurstmeister/zookeeper
    hostname: zookeeper2
    ports:
      - 2182:2182
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2182

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1 # kafka-logs-{hostname}
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
#      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
    volumes:
      - ./docker/kafka1:/kafka
    depends_on:
      - zookeeper1
      - zookeeper2

  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2 # kafka-logs-{hostname}
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
#      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
    volumes:
      - ./docker/kafka2:/kafka
    depends_on:
      - zookeeper1
      - zookeeper2
